apiVersion: v1
kind: ConfigMap
metadata:
  name: people-service-config
  namespace: oficina-people-service
  labels:
    app: people-service
data:
  SPRING_PROFILES_ACTIVE: "prod"
  AWS_REGION: "us-east-1"
  LOG_LEVEL: "INFO"
  DB_PORT: "5432"
  DB_NAME: "peopleservice"
  DB_HOST: "${DB_HOST}"
  NEW_RELIC_APP_NAME: "people-service"
  NEW_RELIC_ENABLED: "true"
  SQS_PEOPLE_EVENTS_QUEUE: "people-events.fifo"
  SQS_CONSUMER_WAIT_TIME_SECONDS: "20"
  SQS_MAX_NUMBER_OF_MESSAGES: "10"
