apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: people-service

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - Deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app: people-service
  app.kubernetes.io/name: people-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: oficina-system

namespace: oficina-people-service
