apiVersion: v1
kind: Secret
metadata:
  name: people-service-secrets
  namespace: oficina-people-service
  labels:
    app: people-service
type: Opaque
data:
  DB_HOST: cGVvcGxlLXNlcnZpY2UtcmRzLnh4eHh4eC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: amp3dF9zZWNyZXRfa2V5XzEyMzQ1Njc4OTA=
  NEW_RELIC_LICENSE_KEY: YWJjMTIzNDU2Nzg5MA==
